### ISSUE TITLE
Slow startup times when using distroless base-image

### ISSUE THREAD

**Issue by ThomasD281** [microsoft/openjdk-docker#55] opened 2022-11-22 13:56 UTC
Hi,
we switched our docker base image from 17-ubuntu to 17-distroless.
Our java spring boot applications itself are untouched.

Unfortunately, we have seen that our application startup times increased significantly (more than 50%) since the switch. 
Can you explain what might be the reason for the increased startup duration?

**Comment by karianna** [comment] 2022-11-22 20:39
@ThomasD281 - A couple of quick questions to get started.

1. Was the 17-ubuntu image the most recent one with our MSFT Build of OpenJDK 17.0.5, or was it a previous, slightly older version?
2. I assume the 17-distroless image that you are using is running the latest MSFT Build of OpenJDK 17.0.5?
3. How you are measuring application startup time?
4. Whereabouts on the spectrum of startup is this?  From cold startup (starting the whole container + JVM for the first time) to warm startup time (Container is running and you've just restarted the JVM or just redeployed the app)
5. Is the deployment environment the same (SKU, vCPU/millicores, Memory available to the container etc)?

**Comment by ThomasD281** [comment] 2022-11-23 06:17
1. The 17-ubuntu was the latest one with openjdk 17.0.5
2. Yes, the 17-distroless image is the latest one as well
3. Checking the application logs for "Started Application in … seconds”
4. cold startup - using kubernetes and each deployment creates new container
5. SKU, millicores and memory config is the same
6. we are running several java spring boot applications (>30) with the distroless image. We can see the same problem in each of our applications.

One example application: old startup time: 19s new startup time: 28s

**Comment by karianna** [comment] 2022-11-26 06:23
@brunoborges and @macarte over to your extra expertise :-)

**Comment by brunoborges** [comment] 2022-11-26 18:36
Can you double check and share here the JVM flags ?

**Comment by karianna** [comment] 2022-11-27 20:43
@ThomasD281 - One further question (if you can share).  Where are you deploying the containers to?  I assume an Azure service (VM, AKS, Azure Container Apps, Azure App Service etc)?

**Comment by ThomasD281** [comment] 2022-11-28 06:39
> @ThomasD281 - One further question (if you can share). Where are you deploying the containers to? I assume an Azure service (VM, AKS, Azure Container Apps, Azure App Service etc)?

Yes, we deploy to aks

**Comment by ThomasD281** [comment] 2022-11-28 06:48
> Can you double check and share here the JVM flags ?

Think we just use these 
`-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true`

**Comment by brunoborges** [comment] 2022-11-28 19:31
@ThomasD281 I did some testing and it appears that the issue is not Ubuntu versus Distroless, but Ubuntu versus CBL Mariner 2.0 (a Microsoft Linux distribution we use in our base image for Distroless).

See this: https://gist.github.com/brunoborges/8bddb05399a858f1048a49c98b6a45ac

In the tests, the startup time of Mariner (regular) versus Mariner Distroless is on average the same, and Ubuntu is 25% faster.

I will check with the Mariner team why it is slower than Ubuntu to start, but for now I will close this ticket as it is not something in our control.

**Comment by brunoborges** [comment] 2022-11-28 19:32
@macarte if you have some bandwidth, can you follow up with the Mariner team, please?

**Closed by brunoborges** 2022-11-28 19:31 UTC

**Comment by brunoborges** [comment] 2022-11-29 01:10
> > Can you double check and share here the JVM flags ?
> 
> Think we just use these `-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true`

By the way, we strongly recommend you set heap sizes and select a Garbage Collector.

**Comment by ThomasD281** [comment] 2022-11-29 06:36
> > > Can you double check and share here the JVM flags ?
> > 
> > 
> > Think we just use these `-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true`
> 
> By the way, we strongly recommend you set heap sizes and select a Garbage Collector.

Any recommended reading regarding these 2 topics - especially garbage collector settings?

**Comment by brunoborges** [comment] 2022-11-29 20:48
> Any recommended reading regarding these 2 topics - especially garbage collector settings?

You can start by watching this: https://www.youtube.com/watch?v=wApqCjHWF8Q&t=5278s
